/* Generated by AN DISI Unibo */ 
package it.unibo.robotactor

import it.unibo.kactor.*
import alice.tuprolog.*
import unibo.basicomm23.*
import unibo.basicomm23.interfaces.*
import unibo.basicomm23.utils.*
import kotlinx.coroutines.CoroutineScope
import kotlinx.coroutines.delay
import kotlinx.coroutines.launch
import kotlinx.coroutines.runBlocking
import it.unibo.kactor.sysUtil.createActor   //Sept2023
//Sept2024
import org.slf4j.Logger
import org.slf4j.LoggerFactory 
import org.json.simple.parser.JSONParser
import org.json.simple.JSONObject


//User imports JAN2024

class Robotactor ( name: String, scope: CoroutineScope, isconfined: Boolean=false, isdynamic: Boolean=false ) : 
          ActorBasicFsm( name, scope, confined=isconfined, dynamically=isdynamic ){

	override fun getInitialState() : String{
		return "s0"
	}
	override fun getBody() : (ActorBasicFsm.() -> Unit){
		//val interruptedStateTransitions = mutableListOf<Transition>()
		//IF actor.withobj !== null val actor.withobj.name� = actor.withobj.method�ENDIF
		val robot = robots.RobotObjForQak("localhost",myself,"logs/robotactor.log")
		 var doingAsynchStep = false   
		 	   val stepTime        = 345L     
		 	   var CurTime         = 0L
		return { //this:ActionBasciFsm
				state("s0") { //this:State
					action { //it:State
						CommUtils.outblue("$name STARTS")
						 clearlog("./logs/robotactor.log") 	//vedi src/main/resources/logback.xml  
						subscribeToLocalActor("robotactor") 
						subscribeToLocalActor("robotactor") 
						CommUtils.outblue("$name subscribe to myself done")
						//genTimer( actor, state )
					}
					//After Lenzi Aug2002
					sysaction { //it:State
					}	 	 
					 transition( edgeName="goto",targetState="work", cond=doswitch() )
				}	 
				state("work") { //this:State
					action { //it:State
						CommUtils.outyellow("$name | work")
						//genTimer( actor, state )
					}
					//After Lenzi Aug2002
					sysaction { //it:State
					}	 	 
					 transition(edgeName="t00",targetState="domove",cond=whenDispatch("move"))
					transition(edgeName="t01",targetState="docmdreq",cond=whenRequest("cmd"))
					transition(edgeName="t02",targetState="handleAsynchStep",cond=whenRequest("step"))
				}	 
				state("domove") { //this:State
					action { //it:State
						if( checkMsgContent( Term.createTerm("move(M)"), Term.createTerm("move(M)"), 
						                        currentMsg.msgContent()) ) { //set msgArgList
								 val Move = payloadArg(0);   
								if(  Move == "h"  
								 ){ robot.halt()          
								}
								if(  Move == "a" || Move == "l"  
								 ){ robot.turnLeft()  
								}
								if(  Move == "d" || Move == "r"  
								 ){ robot.turnRight()  
								}
						}
						//genTimer( actor, state )
					}
					//After Lenzi Aug2002
					sysaction { //it:State
					}	 	 
					 transition( edgeName="goto",targetState="work", cond=doswitch() )
				}	 
				state("handleSonarData") { //this:State
					action { //it:State
						if( checkMsgContent( Term.createTerm("sonar(DISTANCE)"), Term.createTerm("sonar(D)"), 
						                        currentMsg.msgContent()) ) { //set msgArgList
								CommUtils.outgreen("$name | handleSonarData ")
								 var D = payloadArg(0)  
								CommUtils.outblack("$name |  sonarval:distance($D) --- ")
								delay(2000) 
								emit("sonaralarm", "distance($D)" ) 
						}
						returnFromInterrupt(interruptedStateTransitions)
						//genTimer( actor, state )
					}
					//After Lenzi Aug2002
					sysaction { //it:State
					}	 	 
				}	 
				state("docmdreq") { //this:State
					action { //it:State
						if( checkMsgContent( Term.createTerm("cmd(MOVE,T)"), Term.createTerm("cmd(M,T)"), 
						                        currentMsg.msgContent()) ) { //set msgArgList
								 val Move = payloadArg(0)
											   val T    = payloadArg(1).toInt() 
								CommUtils.outyellow("$name | cmd $Move $T")
								if(  Move == "w"  
								 ){ robot.forward(T)        
								}
								if(  Move == "s"  
								 ){ robot.backward(T)       
								}
						}
						//genTimer( actor, state )
					}
					//After Lenzi Aug2002
					sysaction { //it:State
					}	 	 
					 transition(edgeName="t03",targetState="handleVrinfoMsgReply",cond=whenEvent("vrinfo"))
					transition(edgeName="t04",targetState="domovewhilerunning",cond=whenDispatch("move"))
				}	 
				state("domovewhilerunning") { //this:State
					action { //it:State
						if( checkMsgContent( Term.createTerm("move(M)"), Term.createTerm("move(M)"), 
						                        currentMsg.msgContent()) ) { //set msgArgList
								 val Move = payloadArg(0);   
								if(  Move == "h"  
								 ){ robot.halt()          
								}
								if(  Move == "p"  
								 ){ robot.step(stepTime)  
								}
								if(  Move == "a" || Move == "l"  
								 ){ robot.turnLeft()  
								}
								if(  Move == "d" || Move == "r"  
								 ){ robot.turnRight()  
								}
						}
						//genTimer( actor, state )
					}
					//After Lenzi Aug2002
					sysaction { //it:State
					}	 	 
					 transition(edgeName="t05",targetState="handleVrinfoMsgReply",cond=whenEvent("vrinfo"))
					transition(edgeName="t06",targetState="domove",cond=whenDispatch("move"))
				}	 
				state("handleVrinfoMsgReply") { //this:State
					action { //it:State
						 var NOW = 0L; var TDONE = 0L  
						NOW = getCurrentTime()
						CommUtils.outred("$name | handleVrinfoMsgReply $currentMsg doingAsynchStep=$doingAsynchStep")
						if( checkMsgContent( Term.createTerm("vrinfo(SOURCE,INFO)"), Term.createTerm("vrinfo(S,R)"), 
						                        currentMsg.msgContent()) ) { //set msgArgList
								 var S = payloadArg(0)  
								 val R = payloadArg(1)  
								if(  doingAsynchStep  
								 ){if(  S.contains("ko")  
								 ){CommUtils.outcyan("$name | reply asynchstep failed $R")
								 TDONE = NOW - CurTime  
								answer("step", "stepfailed", "stepfailed($TDONE,ok)"   )  
								}
								else
								 {CommUtils.outcyan("$name | reply asynchstep done")
								 answer("step", "stepdone", "stepdone(ok)"   )  
								 }
								 doingAsynchStep = false  
								}
								else
								 {if(  S.contains("ko")  
								  ){answer("cmd", "cmdfailed", "cmdfailed($S,$R)"   )  
								 }
								 else
								  {answer("cmd", "cmddone", "cmddone($S)"   )  
								  }
								 }
						}
						//genTimer( actor, state )
					}
					//After Lenzi Aug2002
					sysaction { //it:State
					}	 	 
					 transition( edgeName="goto",targetState="work", cond=doswitch() )
				}	 
				state("handleAsynchStep") { //this:State
					action { //it:State
						CommUtils.outblue("$name | handleAsynchStep $currentMsg")
						CurTime = getCurrentTime()
						 doingAsynchStep = true   
						if( checkMsgContent( Term.createTerm("step(TIME)"), Term.createTerm("step(T)"), 
						                        currentMsg.msgContent()) ) { //set msgArgList
								 robot.forward(payloadArg(0).toInt() )  
						}
						//genTimer( actor, state )
					}
					//After Lenzi Aug2002
					sysaction { //it:State
					}	 	 
					 transition(edgeName="t07",targetState="handleVrinfoMsgReply",cond=whenEvent("vrinfo"))
				}	 
			}
		}
} 
