/* Generated by AN DISI Unibo */ 
package it.unibo.sonarmock

import it.unibo.kactor.*
import alice.tuprolog.*
import unibo.basicomm23.*
import unibo.basicomm23.interfaces.*
import unibo.basicomm23.utils.*
import kotlinx.coroutines.CoroutineScope
import kotlinx.coroutines.delay
import kotlinx.coroutines.launch
import kotlinx.coroutines.runBlocking
import it.unibo.kactor.sysUtil.createActor   //Sept2023
//Sept2024
import org.slf4j.Logger
import org.slf4j.LoggerFactory 
import org.json.simple.parser.JSONParser
import org.json.simple.JSONObject


//User imports JAN2024

class Sonarmock ( name: String, scope: CoroutineScope, isconfined: Boolean=false, isdynamic: Boolean=false ) : 
          ActorBasicFsm( name, scope, confined=isconfined, dynamically=isdynamic ){

	override fun getInitialState() : String{
		return "s0"
	}
	override fun getBody() : (ActorBasicFsm.() -> Unit){
		//val interruptedStateTransitions = mutableListOf<Transition>()
		//IF actor.withobj !== null val actor.withobj.name� = actor.withobj.method�ENDIF
		 
				var DMIN = 30 
				var dist_rilevata = 0
				var Timer = 2000L
				var stato_allarme = false
		return { //this:ActionBasciFsm
				state("s0") { //this:State
					action { //it:State
						CommUtils.outgreen("$name | starting")
						//genTimer( actor, state )
					}
					//After Lenzi Aug2002
					sysaction { //it:State
					}	 	 
					 transition( edgeName="goto",targetState="rileva", cond=doswitch() )
				}	 
				state("rileva") { //this:State
					action { //it:State
						 dist_rilevata = java.util.Random().nextInt(0, 100 ) 
						CommUtils.outgreen("$name | distanza rilevata = $dist_rilevata")
						if(  !stato_allarme && dist_rilevata <DMIN  
						 ){CommUtils.outgreen("$name | INIZIO stato di allarme")
						 
										var F = 500L
										stato_allarme = true 
						emit("minore", "minore($F)" ) 
						delay(500) 
						emit("go", "go(do)" ) 
						}
						if(  stato_allarme && dist_rilevata >= DMIN  
						 ){ stato_allarme = false  
						CommUtils.outgreen("$name | FINE stato di allarme")
						emit("maggiore", "maggiore(do)" ) 
						delay(500) 
						emit("go", "go(do)" ) 
						}
						//genTimer( actor, state )
					}
					//After Lenzi Aug2002
					sysaction { //it:State
				 	 		stateTimer = TimerActor("timer_rileva", 
				 	 					  scope, context!!, "local_tout_"+name+"_rileva", Timer )  //OCT2023
					}	 	 
					 transition(edgeName="t04",targetState="rileva",cond=whenTimeout("local_tout_"+name+"_rileva"))   
				}	 
			}
		}
} 
