/* Generated by AN DISI Unibo */ 
package it.unibo.firefly

import it.unibo.kactor.*
import alice.tuprolog.*
import unibo.basicomm23.*
import unibo.basicomm23.interfaces.*
import unibo.basicomm23.utils.*
import kotlinx.coroutines.CoroutineScope
import kotlinx.coroutines.delay
import kotlinx.coroutines.launch
import kotlinx.coroutines.runBlocking
import it.unibo.kactor.sysUtil.createActor   //Sept2023
//Sept2024
import org.slf4j.Logger
import org.slf4j.LoggerFactory 
import org.json.simple.parser.JSONParser
import org.json.simple.JSONObject


//User imports JAN2024

class Firefly ( name: String, scope: CoroutineScope, isconfined: Boolean=false, isdynamic: Boolean=true ) : 
          ActorBasicFsm( name, scope, confined=isconfined, dynamically=isdynamic ){

	override fun getInitialState() : String{
		return "s0"
	}
	override fun getBody() : (ActorBasicFsm.() -> Unit){
		//val interruptedStateTransitions = mutableListOf<Transition>()
		//IF actor.withobj !== null val actor.withobj.name� = actor.withobj.method�ENDIF
		   
			   var  X          = 0
			   var  Y          = 0
			   var F		   = java.util.Random().nextLong(500L,2000L )
			   
			   fun setCellCoords( )  {
		     		val coordY = name.replace("firefly_","")    
		      		Y  = coordY.toInt()        
		  		}		
			   
		return { //this:ActionBasciFsm
				state("s0") { //this:State
					action { //it:State
						 setCellCoords( )  
						CommUtils.outmagenta("$name | X=$X Y=$Y  Frequency=$F")
						//genTimer( actor, state )
					}
					//After Lenzi Aug2002
					sysaction { //it:State
					}	 	 
					 transition( edgeName="goto",targetState="flash", cond=doswitch() )
				}	 
				state("flash") { //this:State
					action { //it:State
						forward("cellstate", "cellstate($X,$Y,1)" ,"griddisplay" ) 
						delay(500) 
						forward("cellstate", "cellstate($X,$Y,0)" ,"griddisplay" ) 
						//genTimer( actor, state )
					}
					//After Lenzi Aug2002
					sysaction { //it:State
				 	 		stateTimer = TimerActor("timer_flash", 
				 	 					  scope, context!!, "local_tout_"+name+"_flash", F )  //OCT2023
					}	 	 
					 transition(edgeName="t00",targetState="flash",cond=whenTimeout("local_tout_"+name+"_flash"))   
					transition(edgeName="t01",targetState="nuovaFrequenza",cond=whenEvent("timer"))
				}	 
				state("nuovaFrequenza") { //this:State
					action { //it:State
						if( checkMsgContent( Term.createTerm("timer(NUOVA_F)"), Term.createTerm("timer(F)"), 
						                        currentMsg.msgContent()) ) { //set msgArgList
								 
												val F_string = payloadArg(0)
												F = F_string.toLong()
								CommUtils.outmagenta("$name | cambio frequenza a $F")
								forward("cellstate", "cellstate($X,$Y,0)" ,"griddisplay" ) 
						}
						//genTimer( actor, state )
					}
					//After Lenzi Aug2002
					sysaction { //it:State
					}	 	 
					 transition(edgeName="t02",targetState="flash",cond=whenEvent("go"))
				}	 
			}
		}
} 
